version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    env_file:
      - .env
    environment:
      - RUST_LOG=info
      - STORAGE_TYPE=Sled
      - STORAGE_PATH=/app/data
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - RATE_LIMIT_MAX_REQUESTS=20
      - RATE_LIMIT_WINDOW_SECONDS=3600
    restart: unless-stopped
    volumes:
      - ./presets.yaml:/app/presets.yaml
      - sled_data:/app/data

volumes:
  sled_data: 